server:
  port: 8889
spring:
  datasource:
    master:
##    家里
#    url: jdbc:mysql://localhost:3306/wuxing?Unicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&aserverTimezone=UTC&useSSL=false
#   公司
      url: jdbc:mysql://localhost:3306/huijiankang?Unicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&useSSL=false&serverTimezone=GMT
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
    slave1:
      url: jdbc:mysql://localhost:3306/hmnewproject?Unicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&useSSL=false&serverTimezone=GMT
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
    slave2:
      url: jdbc:mysql://localhost:3306/huijiankang?Unicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&useSSL=false&serverTimezone=GMT
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
mybatis-plus:
  mapper-locations: classpath*:/com/hwq/wudi/*/mapper/xml/*.xml
  type-aliases-package: com.hwq.wudi.*.entity
  configuration:
    map-underscore-to-camel-case: true
#    <!-- 设置当结果集中为null，调用setter(map 为put)方法 -->
    call-setters-on-nulls: true