
server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wuxing?Unicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&aserverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml