server:
  port: 8888
spring:
  datasource:
##    家里
#    url: jdbc:mysql://localhost:3306/wuxing?Unicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&aserverTimezone=UTC&useSSL=false
#   公司
    url: jdbc:mysql://localhost:3306/huijiankang?Unicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&useSSL=false&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        #消费者关闭自动ack，防止消息丢失
        acknowledge-mode: manual
        #单个消费者最多未确认ack的消息数量
        prefetch: 1
#        # 并发消费
#        concurrency: 5
#        max-concurrency: 10
#        #最后一次重试如果仍然异常，是否把消息放回队列，这里手动确认不好使，可以不设置
#        #可以结合死信队列，开启自动ack时，这个配置才会生效
#        default-requeue-rejected: false
#        retry:
#          #开启retry重试机制
#          enabled: true
#          #最大重试次数
#          max-attempts: 3
#          #每次重试间隔时间
#          initial-interval: 5000ms
  redis:
    host: 10.0.97.112
    port: 6379
    database: 5
    jedis:
      pool:
      #最大连接个数
        max-active: 10
        #等待时间
        max-wait: 6000ms
        #最大空闲
        max-idle: 8
        #初始化最小
        min-idle: 5